version: "3.8"

services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - "ZITADEL_DATABASE_POSTGRES_HOST=postgres"
      - "ZITADEL_DATABASE_POSTGRES_PORT=5432"
      - "ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable"
      - "ZITADEL_EXTERNALSECURE=false"
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    restart: "always"
    image: "bitnami/postgresql:16"
    environment:
      - "POSTGRESQL_USERNAME=postgres"
      - "POSTGRESQL_PASSWORD=postgres"
      - "POSTGRESQL_DATABASE=zitadel"
    networks:
      - "zitadel"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/bitnami/postgresql"

networks:
  zitadel:

volumes:
  postgres_data:
