version: "3.7"

services:
  postgres:
    image: "bitnami/postgresql:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: pass
      POSTGRESQL_DATABASE: keycloak
    volumes:
      - "postgres_data:/bitnami/postgresql"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: pass
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_LOG_LEVEL: INFO
      KC_REALM_NAME: starter
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    ports:
      - 8181:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import

volumes:
  postgres_data:
    driver: local
